version: '3.8'

services:
  glite:
    image: echoer/glite
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./compressed:/usr/src/app/compressed
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  uploads:
  compressed: